// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3g0PPk35TGzZAfozTTIHPbIm2sJXp-Ac',
    appId: '1:940910133170:android:56ac686333a0195b3e2eab',
    messagingSenderId: '940910133170',
    projectId: 'funkin-good-time-karaoke',
    storageBucket: 'funkin-good-time-karaoke.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaZIC-kghx6Z4i0biL8sdPXMENMLQkleg',
    appId: '1:940910133170:ios:ecdd9bf2d57986863e2eab',
    messagingSenderId: '940910133170',
    projectId: 'funkin-good-time-karaoke',
    storageBucket: 'funkin-good-time-karaoke.firebasestorage.app',
    iosBundleId: 'com.funkin.karaoke',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaZIC-kghx6Z4i0biL8sdPXMENMLQkleg',
    appId: '1:940910133170:ios:aa99826c2ba7ab093e2eab',
    messagingSenderId: '940910133170',
    projectId: 'funkin-good-time-karaoke',
    storageBucket: 'funkin-good-time-karaoke.firebasestorage.app',
    iosBundleId: 'com.example.funkinkaraokeSinger',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcfS9ugPJZiuEwY7Y-8yMkG8EoF5lBA3M',
    appId: '1:940910133170:web:f7e0082e9473f7363e2eab',
    messagingSenderId: '940910133170',
    projectId: 'funkin-good-time-karaoke',
    authDomain: 'funkin-good-time-karaoke.firebaseapp.com',
    storageBucket: 'funkin-good-time-karaoke.firebasestorage.app',
    measurementId: 'G-53TYRS5DNR',
  );

}